"""update product category

Revision ID: 5f1bd2a54792
Revises: 5dcb67f479e0
Create Date: 2025-06-30 15:36:08.648704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f1bd2a54792'
down_revision: Union[str, None] = '5dcb67f479e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    product_enum = sa.Enum(
        'ELECTRONICS', 'FASHION', 'HOME_APPLIANCES', 'BOOKS', 'BEAUTY',
        'SPORTS', 'GROCERIES', 'TOYS', 'AUTOMOTIVE', 'HEALTH',
        'PET_SUPPLIES', 'BABY_PRODUCTS', 'FURNITURE', 'STATIONERY',
        'GAMING', 'MUSICAL_INSTRUMENTS', 'SOFTWARE',
        name='productcategoryenum'
    )
    product_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('products', sa.Column('category',product_enum , nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'category')
    # ### end Alembic commands ###
